services:
  db:
    image: postgres
    container_name: storymap-db
    environment:
      POSTGRES_DB: storymap
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: