quarkus:
  log:
    category:
      "org.hibernate.orm.boot":
        level: DEBUG
    min-level: TRACE
  #      "io.quarkus.security":
#        level: DEBUG
#      "io.smallrye.jwt":
#        level: DEBUG
#      "io.quarkus.config":
#        level: DEBUG
  rest-client:
    gitlab-api:
      url: ${gitlab.api-url}
      headers:
        - name: PRIVATE-TOKEN
          value: ${gitlab.token}
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/storymap
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  hibernate-orm:
    packages: com.example.entity
    sql-load-script: import.sql
    log:
      sql: true
      bind-parameters: true
    schema-management:
      strategy: drop-and-create
  smallrye-openapi:
    path: /q/openapi
  native:
    resources:
      includes: publicKey.pem

gitlab:
  token: ${GITLAB_TOKEN}
  api-url: https://gitlab.com/api/v4
  project-id: ${GITLAB_PROJECT_ID}

"%dev":
  DB_USER: admin
  DB_PASSWORD: admin
  mp:
   jwt:
      verify:
        publickey:
          location: publicKey.pem
        issuer: https://example.com/issuer
      groups:
        claim: groups
  smallrye:
    jwt:
      sign:
        key:
          location: privateKey.pem

"%prod":
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  mp:
    jwt:
      verify:
        publickey:
          location: publicKey.pem
        issuer: https://example.com/issuer
      groups:
        claim: groups
  smallrye:
    jwt:
      sign:
        key: ${PRIVATE_KEY}
